services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvz-service
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"   # HTTP
      - "${GRPC_PORT}:${GRPC_PORT}"   # gRPC
      - "${METRICS_PORT}:${METRICS_PORT}"   # Prometheus /metrics
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - pvz_net

  db:
    image: postgres:15
    container_name: pvz-db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pvz_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pvz_net

volumes:
  pgdata:

networks:
  pvz_net:
